# Generated by Django 2.0.2 on 2018-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('posted', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
